apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginxdemo
  name: nginxdemo
spec:
  containers:
  - image: nginx
    name: nginxdemo
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
