apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: nginxdemo
  name: nginxdemo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginxdemo
  type: LoadBalancer
status:
  loadBalancer: {}
